CREATE TABLE "supportify_ticket" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supportify_ticket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"projectID" integer NOT NULL,
	"assigneeID" integer,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	"deletedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "supportify_user" RENAME COLUMN "clearkID" TO "clerkID";--> statement-breakpoint
ALTER TABLE "supportify_user" ADD COLUMN "orgID" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "supportify_user" ADD COLUMN "createdAt" timestamp with time zone DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "supportify_user" ADD COLUMN "updatedAt" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "supportify_user" ADD COLUMN "deletedAt" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "supportify_ticket" ADD CONSTRAINT "supportify_ticket_projectID_supportify_project_id_fk" FOREIGN KEY ("projectID") REFERENCES "public"."supportify_project"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supportify_ticket" ADD CONSTRAINT "supportify_ticket_assigneeID_supportify_user_id_fk" FOREIGN KEY ("assigneeID") REFERENCES "public"."supportify_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supportify_user" ADD CONSTRAINT "supportify_user_orgID_supportify_organization_id_fk" FOREIGN KEY ("orgID") REFERENCES "public"."supportify_organization"("id") ON DELETE no action ON UPDATE no action;